### ISSUE TITLE
Example for sorter function

### ISSUE THREAD

**Issue by Beluk** [SnowdogApps/vuepress-plugin-pdf-export#5]
Can you please provide an example how to use the sorter function?

**Comment by Igloczek** [comment]
It's a vanilla JS array sort function

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by Beluk** [comment]
Thank you. For someone else interested in this topic i used it to bring the landing page to the first side of the pdf:

```js
['@snowdog/vuepress-plugin-pdf-export', {
         sorter: function(a, b){  if (a.relativePath == "index.md") return -1; if (b.relativePath == "index.md") return 1;
           return a.attr > b.attr ? -1: 1;}
}]
```
